// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 5
		case r == 39: // [''',''']
			return 6
		case r == 40: // ['(','(']
			return 7
		case r == 41: // [')',')']
			return 8
		case r == 42: // ['*','*']
			return 9
		case r == 43: // ['+','+']
			return 10
		case r == 44: // [',',',']
			return 11
		case r == 45: // ['-','-']
			return 12
		case r == 46: // ['.','.']
			return 13
		case r == 47: // ['/','/']
			return 14
		case r == 48: // ['0','0']
			return 15
		case 49 <= r && r <= 57: // ['1','9']
			return 16
		case r == 58: // [':',':']
			return 17
		case r == 60: // ['<','<']
			return 18
		case r == 61: // ['=','=']
			return 19
		case r == 62: // ['>','>']
			return 20
		case r == 63: // ['?','?']
			return 21
		case 65 <= r && r <= 68: // ['A','D']
			return 22
		case r == 69: // ['E','E']
			return 23
		case r == 70: // ['F','F']
			return 24
		case 71 <= r && r <= 75: // ['G','K']
			return 22
		case r == 76: // ['L','L']
			return 25
		case 77 <= r && r <= 84: // ['M','T']
			return 22
		case r == 85: // ['U','U']
			return 26
		case 86 <= r && r <= 90: // ['V','Z']
			return 22
		case r == 91: // ['[','[']
			return 27
		case r == 93: // [']',']']
			return 28
		case r == 94: // ['^','^']
			return 29
		case r == 95: // ['_','_']
			return 30
		case 97 <= r && r <= 100: // ['a','d']
			return 22
		case r == 101: // ['e','e']
			return 23
		case r == 102: // ['f','f']
			return 31
		case 103 <= r && r <= 107: // ['g','k']
			return 22
		case r == 108: // ['l','l']
			return 25
		case 109 <= r && r <= 115: // ['m','s']
			return 22
		case r == 116: // ['t','t']
			return 32
		case r == 117: // ['u','u']
			return 26
		case 118 <= r && r <= 122: // ['v','z']
			return 22
		case r == 124: // ['|','|']
			return 33
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 34
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 35
		case r == 92: // ['\','\']
			return 36
		default:
			return 37
		}
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 38: // ['&','&']
			return 38
		case r == 94: // ['^','^']
			return 39
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 40
		case r == 92: // ['\','\']
			return 41
		default:
			return 42
		}
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 43
		case r == 69: // ['E','E']
			return 44
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 101: // ['e','e']
			return 44
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 46
		case 48 <= r && r <= 55: // ['0','7']
			return 47
		case 56 <= r && r <= 57: // ['8','9']
			return 16
		case r == 69: // ['E','E']
			return 48
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 49
		case r == 85: // ['U','U']
			return 50
		case r == 88: // ['X','X']
			return 51
		case r == 101: // ['e','e']
			return 48
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 49
		case r == 117: // ['u','u']
			return 50
		case r == 120: // ['x','x']
			return 51
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 46
		case 48 <= r && r <= 57: // ['0','9']
			return 16
		case r == 69: // ['E','E']
			return 48
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 49
		case r == 85: // ['U','U']
			return 50
		case r == 101: // ['e','e']
			return 48
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 49
		case r == 117: // ['u','u']
			return 50
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 60: // ['<','<']
			return 52
		case r == 61: // ['=','=']
			return 53
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 54
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 55
		case r == 62: // ['>','>']
			return 56
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 60
		case r == 45: // ['-','-']
			return 60
		case 48 <= r && r <= 57: // ['0','9']
			return 61
		case 65 <= r && r <= 69: // ['A','E']
			return 58
		case r == 70: // ['F','F']
			return 62
		case 71 <= r && r <= 75: // ['G','K']
			return 58
		case r == 76: // ['L','L']
			return 62
		case 77 <= r && r <= 90: // ['M','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 101: // ['a','e']
			return 58
		case r == 102: // ['f','f']
			return 62
		case 103 <= r && r <= 107: // ['g','k']
			return 58
		case r == 108: // ['l','l']
			return 62
		case 109 <= r && r <= 122: // ['m','z']
			return 58
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case r == 97: // ['a','a']
			return 63
		case 98 <= r && r <= 122: // ['b','z']
			return 58
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 113: // ['a','q']
			return 58
		case r == 114: // ['r','r']
			return 64
		case 115 <= r && r <= 122: // ['s','z']
			return 58
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case r == 124: // ['|','|']
			return 65
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 37
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 35
		case r == 92: // ['\','\']
			return 36
		default:
			return 37
		}
	},
	// S38
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 42
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 40
		case r == 92: // ['\','\']
			return 41
		default:
			return 42
		}
	},
	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 43
		case r == 69: // ['E','E']
			return 66
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 101: // ['e','e']
			return 66
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 67
		case r == 45: // ['-','-']
			return 67
		case 48 <= r && r <= 57: // ['0','9']
			return 68
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 69
		case r == 69: // ['E','E']
			return 70
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 101: // ['e','e']
			return 70
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 46
		case 48 <= r && r <= 55: // ['0','7']
			return 47
		case 56 <= r && r <= 57: // ['8','9']
			return 16
		case r == 69: // ['E','E']
			return 48
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 49
		case r == 85: // ['U','U']
			return 50
		case r == 101: // ['e','e']
			return 48
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 49
		case r == 117: // ['u','u']
			return 50
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 60
		case r == 45: // ['-','-']
			return 60
		case 48 <= r && r <= 57: // ['0','9']
			return 71
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 72
		case 65 <= r && r <= 70: // ['A','F']
			return 72
		case r == 76: // ['L','L']
			return 50
		case r == 85: // ['U','U']
			return 50
		case 97 <= r && r <= 102: // ['a','f']
			return 72
		case r == 108: // ['l','l']
			return 50
		case r == 117: // ['u','u']
			return 50
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 71
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 61
		case 65 <= r && r <= 69: // ['A','E']
			return 58
		case r == 70: // ['F','F']
			return 62
		case 71 <= r && r <= 75: // ['G','K']
			return 58
		case r == 76: // ['L','L']
			return 62
		case 77 <= r && r <= 90: // ['M','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 101: // ['a','e']
			return 58
		case r == 102: // ['f','f']
			return 62
		case 103 <= r && r <= 107: // ['g','k']
			return 58
		case r == 108: // ['l','l']
			return 62
		case 109 <= r && r <= 122: // ['m','z']
			return 58
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 107: // ['a','k']
			return 58
		case r == 108: // ['l','l']
			return 73
		case 109 <= r && r <= 122: // ['m','z']
			return 58
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 116: // ['a','t']
			return 58
		case r == 117: // ['u','u']
			return 74
		case 118 <= r && r <= 122: // ['v','z']
			return 58
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 75
		case r == 45: // ['-','-']
			return 75
		case 48 <= r && r <= 57: // ['0','9']
			return 76
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 68
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 68
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 69
		case r == 69: // ['E','E']
			return 77
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 101: // ['e','e']
			return 77
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 78
		case r == 45: // ['-','-']
			return 78
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 71
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 72
		case 65 <= r && r <= 70: // ['A','F']
			return 72
		case r == 76: // ['L','L']
			return 50
		case r == 85: // ['U','U']
			return 50
		case 97 <= r && r <= 102: // ['a','f']
			return 72
		case r == 108: // ['l','l']
			return 50
		case r == 117: // ['u','u']
			return 50
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 114: // ['a','r']
			return 58
		case r == 115: // ['s','s']
			return 80
		case 116 <= r && r <= 122: // ['t','z']
			return 58
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 100: // ['a','d']
			return 58
		case r == 101: // ['e','e']
			return 81
		case 102 <= r && r <= 122: // ['f','z']
			return 58
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 76
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 76
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 82
		case r == 45: // ['-','-']
			return 82
		case 48 <= r && r <= 57: // ['0','9']
			return 83
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S79
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 100: // ['a','d']
			return 58
		case r == 101: // ['e','e']
			return 84
		case 102 <= r && r <= 122: // ['f','z']
			return 58
		}
		return NoState
	},
	// S81
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
	// S82
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 83
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S83
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 83
		case r == 70: // ['F','F']
			return 45
		case r == 76: // ['L','L']
			return 45
		case r == 102: // ['f','f']
			return 45
		case r == 108: // ['l','l']
			return 45
		}
		return NoState
	},
	// S84
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 57
		case 65 <= r && r <= 90: // ['A','Z']
			return 58
		case r == 95: // ['_','_']
			return 59
		case 97 <= r && r <= 122: // ['a','z']
			return 58
		}
		return NoState
	},
}
