// Code generated by "stringer -type=tokenkind"; DO NOT EDIT.

package expr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[niltoken-0]
	_ = x[errtoken-1]
	_ = x[eoftoken-2]
	_ = x[identtoken-3]
	_ = x[inttoken-4]
	_ = x[floattoken-5]
	_ = x[booltoken-6]
	_ = x[addtoken-7]
	_ = x[subtoken-8]
	_ = x[multoken-9]
	_ = x[quotoken-10]
	_ = x[remtoken-11]
	_ = x[andtoken-12]
	_ = x[nottoken-13]
	_ = x[ortoken-14]
	_ = x[xortoken-15]
	_ = x[shltoken-16]
	_ = x[shrtoken-17]
	_ = x[andnottoken-18]
	_ = x[logicalandtoken-19]
	_ = x[logicalortoken-20]
	_ = x[equaltoken-21]
	_ = x[lessertoken-22]
	_ = x[greatertoken-23]
	_ = x[notequaltoken-24]
	_ = x[lesserequaltoken-25]
	_ = x[greaterequaltoken-26]
	_ = x[leftparentoken-27]
	_ = x[leftbrackettoken-28]
	_ = x[commatoken-29]
	_ = x[periodtoken-30]
	_ = x[rightparentoken-31]
	_ = x[rightbrackettoken-32]
	_ = x[colontoken-33]
	_ = x[ternarytoken-34]
	_ = x[boolkeyword-35]
	_ = x[bytekeyword-36]
	_ = x[float32keyword-37]
	_ = x[float64keyword-38]
	_ = x[intkeyword-39]
	_ = x[int8keyword-40]
	_ = x[int16keyword-41]
	_ = x[int32keyword-42]
	_ = x[int64keyword-43]
	_ = x[uintkeyword-44]
	_ = x[uint8keyword-45]
	_ = x[uint16keyword-46]
	_ = x[uint32keyword-47]
	_ = x[uint64keyword-48]
	_ = x[uintptrkeyword-49]
	_ = x[nilkeyword-50]
}

const _tokenkind_name = "niltokenerrtokeneoftokenidenttokeninttokenfloattokenbooltokenaddtokensubtokenmultokenquotokenremtokenandtokennottokenortokenxortokenshltokenshrtokenandnottokenlogicalandtokenlogicalortokenequaltokenlessertokengreatertokennotequaltokenlesserequaltokengreaterequaltokenleftparentokenleftbrackettokencommatokenperiodtokenrightparentokenrightbrackettokencolontokenternarytokenboolkeywordbytekeywordfloat32keywordfloat64keywordintkeywordint8keywordint16keywordint32keywordint64keyworduintkeyworduint8keyworduint16keyworduint32keyworduint64keyworduintptrkeywordnilkeyword"

var _tokenkind_index = [...]uint16{0, 8, 16, 24, 34, 42, 52, 61, 69, 77, 85, 93, 101, 109, 117, 124, 132, 140, 148, 159, 174, 188, 198, 209, 221, 234, 250, 267, 281, 297, 307, 318, 333, 350, 360, 372, 383, 394, 408, 422, 432, 443, 455, 467, 479, 490, 502, 515, 528, 541, 555, 565}

func (i tokenkind) String() string {
	if i < 0 || i >= tokenkind(len(_tokenkind_index)-1) {
		return "tokenkind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenkind_name[_tokenkind_index[i]:_tokenkind_index[i+1]]
}
